### ISSUE TITLE
Add new probes: nvidia-smi, CUDA-Z and numactl -H

### ISSUE THREAD

**Issue by aponomarenko** [linuxhw/hw-probe#1]
Add new probes nvidia-smi, CUDA-Z and numactl -H as suggested on the OpenMandriva mailing list: http://ml.openmandriva.org/pipermail/om-cooker_ml.openmandriva.org/2016-February/000267.html

**Comment by lvc** [comment]
Fixed by 5eadb6a963a90b739c629ecc27e466faf17805d5.
