### ISSUE TITLE
The reported year is older than the release date of the installed BIOS 

### ISSUE THREAD

**Issue by grahamperrin** [linuxhw/hw-probe#106]
https://bsd-hardware.info/?probe=5a4e53da56#Host shows: 

> `Year | 2013`

This seems to be inconsistent with the year (2019) at <https://bsd-hardware.info/?probe=5a4e53da56&log=dmidecode>

Maybe relevant: this computer <https://bsd-hardware.info/?computer=6fbb1f806232> _did_ have outdated BIOS when first probed. 

----

For the same system before I transferred it from one HP EliteBook 8570p to another: <https://bsd-hardware.info/?computer=8f084339058d> – _2019_.

**Comment by linuxhw** [comment]
This is the approximation of the computer board manufacture year. In the first probe of this computer you have BIOS from 05/20/2013. So 2013 will not be increased if you update the BIOS. The computer is still from 2013.
