### ISSUE TITLE
linuxhw/ but could it work on macOS?

### ISSUE THREAD

**Issue by alexmyczko** [linuxhw/hw-probe#107]
just being curious... i like the stats part, and i am aware it is for hardware support. on the other hand it delivers also stats like http://popcon.debian.org, which http://popcon.ubuntu.com also should but theirs is broken aince 5 years. meanwhile ubuntu has https://ubuntu.com/desktop/statistics which is outdated for 3 years...

**Comment by linuxhw** [comment]
As you know, MacOS is sold together with hardware. So every hardware configuration is supported and therefore we don't need a database of supported/unsupported hardware. But it is still possible to create a database in degenerate form to store reliable / unreliable configurations (taking into account broken drives, WiFi cards, batteries, etc.). The hardware probe tool will operate just like a new hardware lister on MacOS.

We can host MacOS probes on https://bsd-hardware.info the same way as for all other BSD derivatives.

I will gladly do it if there are interested people who can give me a new MacBook ;)

**Comment by alexmyczko** [comment]
```
perl hw-probe.pl -all -upload
mkdir /root: Read-only file system at hw-probe.pl line 17031.
```

**Comment by Low-power** [comment]
After adding `darwin` to `@KNOWN_BSD`:
```
# uname -a
Darwin x 10.3.0 Darwin Kernel Version 10.3.0: Fri Feb 26 11:58:09 PST 2010; root:xnu-1504.3.12~1/RELEASE_I386 i386
# perl hw-probe.pl -all -maximal -upload 
WARNING: 'dmidecode' package is not installed
Probe for hardware ... Ok
Reading logs ... invalid option or syntax: -b
top usage: top
		[-a | -d | -e | -c <mode>]
		[-F | -f]
		[-h]
		[-i <interval>]
		[-l <samples>]
		[-ncols <columns>]
		[-o <key>] [-O <secondaryKey>]
		[-R | -r]
		[-S]
		[-s <delay>]
		[-n <nprocs>]
		[-stats <key(s)>]
		[-pid <processid>]
		[-user <username>]
		[-U <username>]
		[-u]

Ok
WARNING: failed to detect EDID
ERROR: not enough info collected
ERROR: failed to upload probe
```

**Comment by sebma** [comment]
@Low-power `dmidecode` can be installed using [MacPorts](https://ports.macports.org/) : `sudo port install dmidecode`
