### ISSUE TITLE
PRIVACY: hw-probe uploads without user consent

### ISSUE THREAD

**Issue by sonnyp** [linuxhw/hw-probe#110]
https://discourse.flathub.org/t/please-remove-hardware-probe-it-is-not-a-desktop-application-and-has-surprising-network-activity/1803

Please do not upload without user consent - no matter if it's from GUI / desktop file, CLI or `flatpak run org.linux_hardware.hw-probe `

**Comment by sonnyp** [comment]
https://github.com/linuxhw/hw-probe/issues/100

**Comment by linuxhw** [comment]
Hello!

Thanks for reporting this!

I want to implement some user interaction since 2018 with no luck: https://gitlab.gnome.org/GNOME/gnome-software/issues/552

Need to fix this flatpak bug first. It's a blocker for such feature.

BTW: why people don't read the description of the package?

**Comment by linuxhw** [comment]
I’ve described clearly how the app works in a new build: https://flathub.org/builds/#/builders/32/builds/67237

**Comment by linuxhw** [comment]
Fixed by adding the GUI.
