### ISSUE TITLE
Add dump of ACPI table

### ISSUE THREAD

**Issue by mikhailnov** [linuxhw/hw-probe#12]
Add output of
```acpidump```
(Debian/Ubuntu package acpica-tools to be added to ```debian/control```)
Linux kernel developers often ask for it to develop a driver for a rare semi-mobile device.

**Comment by lvc** [comment]
This is already implemented by the following options:

  -dump-acpi
      Probe for ACPI table.
  
  -decode-acpi
      Decode ACPI table.

Please do not include this data to each probe of the computer because it takes extra space on the storage server.

Thank you.

**Comment by mikhailnov** [comment]
Ok, thank you very much!
