### ISSUE TITLE
Why hwstat and lscpu are excluded on FreeBSD?

### ISSUE THREAD

**Issue by danfe** [linuxhw/hw-probe#120]
Now there's this code:
```perl
    if($Sys{"System"}!~/$KNOWN_BSD_ALL/)
    { # Unknown FreeBSD-based
        @NeedProgs = grep {$_!~/hwstat|lscpu/} @NeedProgs;
    }
```
Because FreeBSD is not listed on `@KNOWN_BSD`, both `hwstat` and `lscpu` are excluded from `@NeedProgs` while there are actually available and listed as port's dependencies.  I've added `freebsd` manually to the list of known BSDs, but I wonder why it's not there by default.

**Comment by linuxhw** [comment]
Fixed by fc68788468351138477f6ad71d6f4cf717e3810b

Thank you!
