### ISSUE TITLE
edid-decode is available on FreeBSD

### ISSUE THREAD

**Issue by danfe** [linuxhw/hw-probe#121]
Currently, `edid-decode` seems to be Linux-only, but it's also available on FreeBSD as `sysutils/edid-decode` port/package.  The difference is that on Linux, it can parse `/sys/class/drm/*/edid` files, while on FreeBSD it should get EDID data from X.Org log file or `xrandr --prop` output.

**Comment by linuxhw** [comment]
The `edid-decode` is executed on the server side. It's not required to be installed on the client side. The Xorg.log is collected on BSD and already analyzed for EDID, so nothing to be implemented here. See https://github.com/linuxhw/hw-probe/blob/master/hw-probe.pl#L8163

Thanks!
