### ISSUE TITLE
Where is actual database of probes stored?

### ISSUE THREAD

**Issue by ghost** [linuxhw/hw-probe#122]
Hello. Where is the database with all probes stored? Somewhere you said it's on github, but here is only statistics in SVG format. Is it on your server or maybe it's private github repo, or what?

**Comment by linuxhw** [comment]
The data is buffered in the compute node and then classified and dumped to several GitHub repositories:

Linux data: https://github.com/linuxhw?tab=repositories
BSD data: https://github.com/bsdhw?tab=repositories

E.g. dmidecode from a probe is dumped to https://github.com/linuxhw/DMI, smartctl is dumped to https://github.com/linuxhw/SMART and so on.
