### ISSUE TITLE
zswap from /proc/cmdline is unnecessary anonymized as zxxxx

### ISSUE THREAD

**Issue by mailinglists35** [linuxhw/hw-probe#128]
https://linux-hardware.org/?probe=3dc84dc8ff&log=grub
GRUB_CMDLINE_LINUX="[...] zXXXX.compressor=zstd zXXXX.enabled=1 [...]"

system:

cat /proc/cmdline
[...] zswap.compressor=zstd zswap.enabled=1

**Comment by linuxhw** [comment]
Fixed by 51a885bea191c3b3c0a79007ea505d08620ed244. Thanks!
