### ISSUE TITLE
Ubuntu PPA 

### ISSUE THREAD

**Issue by mikhailnov** [linuxhw/hw-probe#14]
Here is a PPA: https://launchpad.net/~mikhailnov/+archive/ubuntu/hw-probe
I hope that I will be able to maintain it further, you can add it to INSTALL and README]
```
sudo add-apt-repository ppa:mikhailnov/hw-probe
sudo apt update
sudo apt install hw-probe
```

**Comment by lvc** [comment]
Great! Thanks a lot!

Commit: 6be3da363e09f4ac0c7adf4d7661c15f14a90835.
