### ISSUE TITLE
hw-probe seems to leak NVME EUI

### ISSUE THREAD

**Issue by driver1998** [linuxhw/hw-probe#140]
Not sure if it is concerning, but the EUI64 IDs of NVMe drives show up in probe reports.

For example:
https://linux-hardware.org/?probe=4386ec3fb8&log=dev

search for nvme-eui.

**Comment by Ricky-Tigg** [comment]
_Extract:_
```
/dev/disk/by-id/nvme-eui.XXXXXXXXXXXXXXXX -> ../../nvme0n1
/dev/disk/by-id/nvme-eui.XXXXXXXXXXXXXXXX-part1 -> ../../nvme0n1p1
```
No private information.

**Comment by driver1998** [comment]
Noticed this a while back, the issue might have already been fixed.
