### ISSUE TITLE
ERROR: failed to upload probe

### ISSUE THREAD

**Issue by multicast** [linuxhw/hw-probe#154]
The `curl` when using `hw-probe -all -upload` returns

```
WARNING: failed to detect EDID
ERROR: failed to upload probe
```

Note that edid files are empty, there is no display unit connected. The run without `-upload` works well and does save probe locally, but such probe cannot be uploaded.

**Comment by linuxhw** [comment]
The failure ‘not allowed to upload more probes’ is temporarily. It just means that you are locked out for a few hours.

**Comment by multicast** [comment]
I did try after few hours with the same result:
```
WARNING: failed to detect EDID
ERROR: failed to upload probe
```
