### ISSUE TITLE
Add an option to generate HTML view of the probe

### ISSUE THREAD

**Issue by aponomarenko** [linuxhw/hw-probe#2]
It would be handy to add a new option of the tool to generate a local HTML page to view the devices list and logs in the probe.

See http://ml.openmandriva.org/pipermail/om-cooker_ml.openmandriva.org/2016-February/000269.html for more info.

**Comment by lvc** [comment]
Done by `-import` option:

    sudo hw-probe -import DIR

This will generate/update offline index of all probes created on the computer to `DIR`.
