### ISSUE TITLE
Mount points can reveal private information

### ISSUE THREAD

**Issue by jvarho** [linuxhw/hw-probe#26]
The boot.log file uploaded (at least) includes information on the location of mount points, like "Mounting /media/ssd" on my ubuntu 16.04 system. These can include private information, e.g. my fstab includes several mounts in my home directory, revealing the username.

Does not seem like these add any value, so they could be stripped from the log or replaced with dummy names.

**Comment by linuxhw** [comment]
Fixed on server. Need to fix this in the hw-probe too.

Thanks a lot!

**Comment by linuxhw** [comment]
Fixed by eab9bd696532f8d157fadb3ae06093bd8d92ad10.
