### ISSUE TITLE
Gentoo: failed to detect Linux distribution

### ISSUE THREAD

**Issue by drunkard** [linuxhw/hw-probe#3]
./hw-probe.pl -all -upload -id MSI -group 5ebeb48a46d163e6
WARNING: failed to detect Linux distribution
Probe for hardware ... Ok
Reading logs ... Ok
Uploaded to DB, Thank you!
Probe URL (Private): http://linux-hardware.org/index.php?probe=404f145917&token=0da169a0e24278f2
Probe URL (Public):  http://linux-hardware.org/index.php?probe=404f145917

Distribution detect should be work, I got:
>$ cat /etc/os-release
>NAME=Gentoo
>ID=gentoo
>PRETTY_NAME="Gentoo/Linux"
>ANSI_COLOR="1;32"
>HOME_URL="http://www.gentoo.org/"
>SUPPORT_URL="http://www.gentoo.org/main/en/support.xml"
>BUG_REPORT_URL="https://bugs.gentoo.org/"

**Comment by lvc** [comment]
Hello,

Fixed by the commit 0015b3d6a1b57cada64b7230d2e0761f0e9628db.

Thank you.
