### ISSUE TITLE
New release in future?

### ISSUE THREAD

**Issue by ConiKost** [linuxhw/hw-probe#36]
Any plans for a new release in future?

**Comment by lvc** [comment]
Yes, 1.5, I hope this winter.

**Comment by linuxhw** [comment]
See https://github.com/gentoo/gentoo/pull/10246#issuecomment-564851892

**Comment by linuxhw** [comment]
Started to prepare the changelog of 1.5. Hope to release next week.

**Comment by linuxhw** [comment]
Released: https://github.com/linuxhw/hw-probe/releases/tag/1.5

Thanks a lot for your help.
