### ISSUE TITLE
How to flag a device as not working properly

### ISSUE THREAD

**Issue by mrwunderbar666** [linuxhw/hw-probe#37]
Hi,

is there any way that I can report a device as not working properly. I have a case where linux loaded a driver for my audio, but it is not working 100% as expected.

**Comment by mrwunderbar666** [comment]
I didn't see the big green review button, sorry

**Comment by linuxhw** [comment]
Hi,

You need to open the probe URL from the same device right after the probe is uploaded. In this case you will be authorized to see the green review button.

If this doesn't work please post your IP and probe ID to info@linux-hardware.org and I'll check what is going wrong.

Thanks.

**Comment by mrwunderbar666** [comment]
It worked out fine, thanks!
