### ISSUE TITLE
how do I remove my sshfs fstab entry from hwprobe on website

### ISSUE THREAD

**Issue by Mannshoch** [linuxhw/hw-probe#39]
on my hw-probe I have some sshfs entrys in this entries I could see the server with Username.
also hw-probe transfered the # Comments from fstab which contain sensitive Information which I need to modify my sshfs.
please remove all comments on fstab entries

**Comment by linuxhw** [comment]
Please report your probe id to info@linux-hardware.org

Thanks!

**Comment by linuxhw** [comment]
Found and fixed.

**Comment by Mannshoch** [comment]
Oh cool. You removed all Comments from all fstab in your database. 
Is hw-probe already updated to not collecting comments ?

**Comment by linuxhw** [comment]
> Oh cool. You removed all Comments from all fstab in your database.
> Is hw-probe already updated to not collecting comments ?

Yep: https://github.com/linuxhw/hw-probe/commit/be7fd790e03e3c8fe1e978a652859e45fa3aee57

It will be a part of 1.5.

Thanks.

**Comment by linuxhw** [comment]
> Oh cool. You removed all Comments from all fstab in your database.
> Is hw-probe already updated to not collecting comments ?

Moreover, fstab is not collected by default in 1.5.
