### ISSUE TITLE
Sensetive data leak from grub config

### ISSUE THREAD

**Issue by KawaiDesu** [linuxhw/hw-probe#41]
Hello.
As I can see, hw-probe cuts out device mapper device names (for example rewrites `/dev/mapper/asdfg` into `/dev/mapper/XXXXXX`), but it's worth nothing because it could leak from grub configuration file:
`GRUB_CMDLINE_LINUX="<blabla> root=/dev/mapper/asdfg <some_other_options>"`

**Comment by linuxhw** [comment]
Fixed on both server and client.

Thanks a lot!
