### ISSUE TITLE
privacy violation: static IPV6 address is logged

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [linuxhw/hw-probe#43]
IPV6 addresses under "ifconfig" are [not properly scrubbed](https://linux-hardware.org/index.php?probe=fb4890a4dd&log=ifconfig)

/128 addresses are visible!

**Comment by linuxhw** [comment]
Hello,

This is now fixed by the commit 0fd5fc5c1c008285650d1909edabe57bf8608ab3.

Thanks!
