### ISSUE TITLE
[Feature request] Please anonymize snap mounts

### ISSUE THREAD

**Issue by LoveIsGrief** [linuxhw/hw-probe#46]
/snap/core, /snap/spotify, /snap/keepassxc etc. can all be seen in the output. `/media/` mounts are anonymized and it would be great if the `/snap/` mounts were too.

**Comment by linuxhw** [comment]
Fixed by the commit eda229cdf20f98d3f4016d2a7b22c14995c968ab.

Thanks a lot!
