### ISSUE TITLE
xorg.log contains hostname

### ISSUE THREAD

**Issue by sunhasgothishaton** [linuxhw/hw-probe#48]
I ran the hw-probe without -upload. When I checked the logs, HOSTNAME is in xorg.log with more than one line of
Current Operating System: Linux <HOSTNAME> ...

Thanks,
Rob

**Comment by linuxhw** [comment]
Did you tried old `1.4` or latest `1.5` version of `hw-probe`?

**Comment by sunhasgothishaton** [comment]
I used version 1.5 using appimage hw-probe-1.5-148-x86_64.AppImage

**Comment by linuxhw** [comment]
What is your Linux distribution name and version?

Thanks.

**Comment by sunhasgothishaton** [comment]
I'm using xubuntu 19.10

**Comment by linuxhw** [comment]
Fixed by b36aef525dc44052f3e168b7f066567ba9350227.

Thanks a lot!

**Comment by sunhasgothishaton** [comment]
That's fantastic, thanks for the quick fix. This is a great project.
