### ISSUE TITLE
Hardware probe says I use Manjaro XFCE, but I'm running KDE

### ISSUE THREAD

**Issue by dginovker** [linuxhw/hw-probe#50]
I've installed XFCE in the past, but it's been a long time since I've used it. Here's a link to my probe: https://linux-hardware.org/?probe=86410e30f4

**Comment by linuxhw** [comment]
Hello,

This is now fixed. Please use

    sudo -E hw-probe -all -upload

for better identifying of the DE.

Thanks a lot!

**Comment by grahamperrin** [comment]
Smart! I would never have guessed. 

@linuxhw aside from the DE, is there any other aspect that's truer with sudo as the logged in user, than as root _without_ sudo?

**Comment by linuxhw** [comment]
AFAIK, DE is the only attribute that requires `sudo -E`.
