### ISSUE TITLE
Can’t run hw-probe

### ISSUE THREAD

**Issue by kocoman2** [linuxhw/hw-probe#53]
I am in ubuntu 19.10 and get this error

Executing hw-probe -all -upload

ERROR: failed to detect Linux distribution

ERROR: Make sure required Snap interfaces are connected:

    for i in hardware-observe system-observe block-devices log-observe upower-observe physical-memory-observe network-observe raw-usb mount-observe opengl;do sudo snap connect hw-probe:$i :$i; done
root@k:~# 

Thanks

**Comment by linuxhw** [comment]
Hi,

What happens after connecting these interfaces?

Please execute the above command in your terminal and re-run the `hw-probe -all -upload`.

Thanks.

**Comment by linuxhw** [comment]
Also please try https://packages.ubuntu.com/focal/hw-probe instead of snap.

See https://wiki.ubuntu.com/Hardware_probe
