### ISSUE TITLE
wrong info

### ISSUE THREAD

**Issue by alexmyczko** [linuxhw/hw-probe#54]
https://linux-hardware.org/?probe=a230cb590f

DE | Cinnamon THAT IS SO WRONG. ->I run Windowmaker with GNUstep 
Type | main server. -> Just a Workstation/Desktop?

**Comment by linuxhw** [comment]
Identifying of DE is fixed.

Identifying of Type is done by `dmidecode`. `Main Server Chassis` form-factor name is embedded to your motherboard.

Thanks a lot!

> https://linux-hardware.org/?probe=a230cb590f
> 
> DE | Cinnamon THAT IS SO WRONG. ->I run Windowmaker with GNUstep
> Type | main server. -> Just a Workstation/Desktop?
