### ISSUE TITLE
add debug mode

### ISSUE THREAD

**Issue by mikhailnov** [linuxhw/hw-probe#6]
Maybe it is possible to add a flag for hw-probe, which would turn on Perl debug output? For example, on one of my machines, probing gets stuck:
$ su
Пароль: 
root@Mikhail-MSK-PC:/tmp/hw-probe# hw-probe -all -upload -id M_msk1
Probe for hardware ... hw-probe -all -upload^C
root@Mikhail-MSK-PC:/tmp/hw-probe# ^C
root@Mikhail-MSK-PC:/tmp/hw-probe# hw-probe -all -upload
Probe for hardware ... 

And I cannot debug it.

**Comment by lvc** [comment]
Hi,

Try `-list` option to list executed probes:

    hw-probe -all -upload -id M_msk1 -list

Thank you.
