### ISSUE TITLE
hw-probe uses insane amounts of memory

### ISSUE THREAD

**Issue by QuImUfu** [linuxhw/hw-probe#64]
As soon as hw-probe reaches a log file it starts to use up at least as much memory as the file is big. As some of the log files probed are >4GiB, this creates an out of memory problem on my PC.  
Maybe the files should be mmap'd instead of read completely to memory.

**Comment by bsdhw** [comment]
Which particular log files you mean?

Thanks.

**Comment by QuImUfu** [comment]
boot.log, maybe others that come later. (had to kill hw-probe)

**Comment by bsdhw** [comment]
Fixed by commit 791646fa2bfdb2be4ff07439364f8da499829e80.
