### ISSUE TITLE
add support for gathering info on Linux kernel display devices using drm_info

### ISSUE THREAD

**Issue by pabs3** [linuxhw/hw-probe#67]
The [drm_info](https://github.com/ascent12/drm_info) project by @ascent12 gathers info on Linux kernel Direct Rendering Manager (DRM) devices. It supports JSON and plain text output and works as non-root. The [drmdb](https://drmdb.emersion.fr/) database gathers info on GPUs and DRM devices, but it would be good to have that information in the linux-hardware.org database too.

**Comment by bsdhw** [comment]
Fixed by commit 3495752099333da2f27abc02f3d5b68151a20574.

Thank you!
