### ISSUE TITLE
Add distribution popularity chart to the website.

### ISSUE THREAD

**Issue by vesterlay** [linuxhw/hw-probe#70]
Adding such a chart would definitely encourage to make the test.

**Comment by alexmyczko** [comment]
this? https://linux-hardware.org/index.php?view=os_name

**Comment by vesterlay** [comment]
Lol, I didn't find it. Sorry for the inconvenience.

**Comment by bsdhw** [comment]
See also: https://linux-hardware.org/index.php?view=os_family
