### ISSUE TITLE
Please add "-m" to your "inxi" command inside your "hw-probe" script to also output the memory info

### ISSUE THREAD

**Issue by sebma** [linuxhw/hw-probe#71]
Hi,
Your `inxi` commands inside your `hw-probe` Perl script are missing the output of the memory info : 
```perl
$ grep "inxi " $(which hw-probe)
            $Inxi = runCmd("inxi -Fxxxz --no-host 2>&1");
            $Inxi = runCmd("inxi -Fxz -c 0 -! 31 2>&1");
```
Can you please add `-m` to your `inxi` commands inside your `hw-probe` Perl script ?

**Comment by linuxhw** [comment]
Fixed by commit c8a19268576a8f1c20279a185443ca87c1a5f8fd

**Comment by sebma** [comment]
@linuxhw Thanks man. BTW : Why do you use a vicious smile tux as an avatar, do you plan to sell the data collected on https://linux-hardware.org ?

**Comment by linuxhw** [comment]
@sebma The collected data is publicly available in multiple repositories: https://github.com/linuxhw?tab=repositories

The icon was introduced by original authors of the site in 2005 and saved for historical reasons: http://web.archive.org/web/20051024143339/http://linux-hardware.org/

**Comment by sebma** [comment]
@linuxhw Oh I see. I forgot this collected data was anonymous.
Thanks for your explanation.
Keep up the good work.
God bless you.
