### ISSUE TITLE
Pine Microsystems devices have incorrect type

### ISSUE THREAD

**Issue by FedericoCeratto** [linuxhw/hw-probe#78]
Pine Microsystems devices are classified as SoC, however:

Pinebook Pro should be notebook/laptop, see: https://linux-hardware.org/index.php?computer=7c3aff4274c6

Pinephone should be smartphone, see https://linux-hardware.org/index.php?computer=cf6d72b07c54

Thanks

**Comment by linuxhw** [comment]
This is now fixed. Thanks a lot for your help!
