### ISSUE TITLE
Server-side sources

### ISSUE THREAD

**Issue by vazhnov** [linuxhw/hw-probe#79]
Hi!
Thank you very much for this great project.
I couldn't find server side sources. Are they published?
Web interface looks pretty good and it would be cool to have possibility to create an own instance for private use.

**Comment by linuxhw** [comment]
Hi!

A lot of work needs to be done to clean up the code before releasing server side sources. I have no time for this currently.

**Comment by vazhnov** [comment]
@linuxhw , how about to ask somebody from community to help with code cleanup before publishing? Maybe I can help with this.

**Comment by linuxhw** [comment]
Not possible for security reasons.
