### ISSUE TITLE
Consider presenting date and time of the probe, near the head of the page

### ISSUE THREAD

**Issue by grahamperrin** [linuxhw/hw-probe#85]
Please, can you show the date and time?

It can be found in logs, but that's not as user-friendly as presenting it (for example) near the head of the main page. 

As a workaround I have been using Diigo to date some of my probes, for example: 

![image](https://user-images.githubusercontent.com/192271/105564241-39c96e80-5d19-11eb-8199-a5c1c97dbdb6.png)

![image](https://user-images.githubusercontent.com/192271/105564265-55347980-5d19-11eb-998f-a915832c3d5f.png)

**Comment by grahamperrin** [comment]
Gentle bump …

**Comment by linuxhw** [comment]
Working on it ...

**Comment by linuxhw** [comment]
Added a tooltip for the title. Have not found a better place for it on the page yet to not to overload it.

![BSDHW-21](https://user-images.githubusercontent.com/15686469/113415633-4c6ebc80-93c8-11eb-99b5-177450989b9e.png)
