### ISSUE TITLE
2018 is the wrong year for HWid 57551 (HP EliteBook 8570p)

### ISSUE THREAD

**Issue by grahamperrin** [linuxhw/hw-probe#87]
https://bsd-hardware.info/?computer=57551b6dfdc4 nine probes, at the time of writing (all FreeBSD-based systems).

It's not immediately clear from HP's https://support.hp.com/gb-en/document/c03393945 but this hardware is much older than 2018. 

QuickSpecs (DA - 14304 Worldwide — Version 16 — June 6, 2013) for HP EliteBook 8470p and HP EliteBook 8570p:

* https://web.archive.org/web/20150906211950/http://www8.hp.com:80/h20195/v2/GetPDF.aspx/c04163744.pdf 

– 2013 is probably a suitable date.

**Comment by linuxhw** [comment]
How can we detect 2013 in the system? Please suggest a command line.

2018 is the last BIOS update year.

**Comment by grahamperrin** [comment]
> 2018 is the last BIOS update year.

Ah, I wasn't aware. If I missed some documentation about how the date is calculated, sorry. 

I can't think of a way to _detect_ the ages of computers so probably best to close this issue, if I learn of a way we can reopen. Apologies for the noise.
