### ISSUE TITLE
[Documentation] Instructions for installing Snap version in classic mode are incorrect

### ISSUE THREAD

**Issue by leogama** [linuxhw/hw-probe#88]
[This segment](https://github.com/linuxhw/hw-probe/blob/master/README.md#classic-snap) of the instructions to "Run without Installing" gives alternatives for installing HW Probe in Snap confinement. It is reasonably detailed, but one step that instructs the user to connect the snap to a list of system interfaces in 'classic confinement' is unnecessary as the linked version of HW Probe (1.4-2) doesn't use this feature.

Commit https://github.com/linuxhw/hw-probe/commit/5f467da3e56eb6bdd24ca16874c7e219be331852 introduced 'strict confinement' for the snap package in version 1.4-6. Since the 1.4-2 version's `snapcraft.yaml` file doesn't list any plugs (connections), the indicated `snap connect` commands produce a list of errors.

**Comment by linuxhw** [comment]
Fixed by commit bd65243ea872e0fb762d50522c436bff0f5822b9

Thank you!
