### ISSUE TITLE
Do not recommend partial upgrades on Arch Linux

### ISSUE THREAD

**Issue by FinishedFragment** [linuxhw/hw-probe#89]
https://github.com/linuxhw/hw-probe/blob/master/INSTALL.md#install-on-arch-linux instructs the user to do a [partial upgrade](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) which can seriously break your system. Change `-Sy` to either `-Syu` or `-S`, or just link to [this article](https://wiki.archlinux.org/index.php/Help:Reading#Installation_of_packages) describing how to install packages.

Also see: https://gist.github.com/vodik/5660494

**Comment by linuxhw** [comment]
Fixed by commit 985fb8df550be1ca9c55a3606ef62883fb9ae556.

Thank you!
