### ISSUE TITLE
Appimage offline mode

### ISSUE THREAD

**Issue by Moltkex** [linuxhw/hw-probe#94]
Hi, 
I downloaded **hw-probe-1.5-164-x86_64.AppImage** and wanted to try and see if the offline mode as described here https://github.com/linuxhw/hw-probe#offline-view worked but got `ERROR: requires perl-Data-Dumper module` I installed `libdata-dumper-simple-perl` to no avail. This is on Debian testing. Is it possible with the appimage? Or is it only possible after installing hw-probe? Thanks.

**Comment by linuxhw** [comment]
Hi,

You don't need `libdata-dumper-simple-perl`. The Data-Dumper module is included to Perl base package in Debian.

Probably we need to add this module to the appimage for this option to work.

Thanks.

**Comment by Moltkex** [comment]
> Hi,
> 
> You don't need `libdata-dumper-simple-perl`. The Data-Dumper module is included to Perl base package in Debian.
> 
> Probably we need to add this module to the appimage for this option to work.
> 
> Thanks.

Ah, I see.  So, just to clarify, at this very moment, the offline mode doesn't work with the appimage? 
Thanks for your reply.

**Comment by linuxhw** [comment]
Hm, the Data-Dumper module is already included to the appimage... Looks like incorrect installation of this module.

**Comment by linuxhw** [comment]
> > Hi,
> > You don't need `libdata-dumper-simple-perl`. The Data-Dumper module is included to Perl base package in Debian.
> > Probably we need to add this module to the appimage for this option to work.
> > Thanks.
> 
> Ah, I see. So, just to clarify, at this very moment, the offline mode doesn't work with the appimage?
> Thanks for your reply.

Yep. Install this deb package instead: http://ftp.br.debian.org/debian/pool/main/h/hw-probe/hw-probe_1.5-1_all.deb

Thanks.

**Comment by Moltkex** [comment]
> > > Hi,
> > > You don't need `libdata-dumper-simple-perl`. The Data-Dumper module is included to Perl base package in Debian.
> > > Probably we need to add this module to the appimage for this option to work.
> > > Thanks.
> > 
> > 
> > Ah, I see. So, just to clarify, at this very moment, the offline mode doesn't work with the appimage?
> > Thanks for your reply.
> 
> Yep. Install this deb package instead: http://ftp.br.debian.org/debian/pool/main/h/hw-probe/hw-probe_1.5-1_all.deb
> 
> Thanks.

It's available in Testing repos so I'll install using apt. 
Thanks

**Comment by linuxhw** [comment]
I could not get it to work and turned off this function in the AppImage. Use other probe methods instead: https://github.com/linuxhw/hw-probe#install

Thank you.

**Comment by Moltkex** [comment]
> I could not get it to work and turned off this function in the AppImage. Use other probe methods instead: https://github.com/linuxhw/hw-probe#install
> 
> Thank you.

I did. I installed the pkg from testing repos and uploaded my probe already :grin: 
Thank you.
