### ISSUE TITLE
Systemctl showing processes running as user!

### ISSUE THREAD

**Issue by Arjab** [linuxhw/hw-probe#99]
Systemd-services running as normal user and not system-wide are listed as "service@user.service" and therefore the username is listed and not erased by hw-probe.

**Comment by linuxhw** [comment]
Please provide probe id in the private message to info@linux-hardware.org

Thanks!

**Comment by Arjab** [comment]
[Fixed](https://github.com/linuxhw/hw-probe/commit/15ad960dbeff3d8f951841d258c79db1b0632cf5)
